<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>me.Superbility</groupId>
    <artifactId>SuperReport</artifactId>
    <version>1.0</version>
    <packaging>jar</packaging>

    <name>SuperReport</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>

    <build>
        <directory>C:\Users\Aidan\SuperReportBuild</directory>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.4</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <minimizeJar>true</minimizeJar>
                            <artifactSet>
                                <!-->
                                <excludes>
                                    <exclude>club.*</exclude>
                                    <exclude>gnu.trove.*</exclude>

                                    <exclude>com.google.*</exclude>
                                    <exclude>com.avaje.ebean.*</exclude>
                                    <exclude>com.avaje.ebeaninternal.*</exclude>

                                    <exclude>org.spigotmc.*</exclude>
                                    <exclude>org.json.*</exclude>
                                    <exclude>org.yaml.*</exclude>
                                    <exclude>org.bukkit.*</exclude>
                                    <exclude>org.hamcrest.*</exclude>

                                    <exclude>net.md_5.bungee.*</exclude>
                                    <exclude>net.java.*</exclude>
                                    <exclude>net.sf.*</exclude>

                                    <exclude>commons-lang.*</exclude>

                                    <exclude>junit.*</exclude>

                                    <exclude>assets.minecraft.*</exclude>
                                </excludes>
                                -->
                                <includes>
                                    <include>me.Superbility.*</include>
                                    <include>net.dv8tion</include>
                                    <include>com.squareup.*</include>
                                    <include>org.slf4j</include>
                                    <include>org.apache.commons</include>
                                    <include>org.jetbrains.kotlin</include>
                                    <include>com.neovisionaries</include>
                                    <include>com.fasterxml.jackson.core</include>
                                    <include>gnu.trove</include>
                                    <include>gnu.trove.*</include>
                                    <include>net.sf.trove4j</include>
                                </includes>
                            </artifactSet>

                            <!-->
                            <artifactSet>
                                <excludes>
                                    <exclude>club.*</exclude>
                                    <exclude>com.fasterxml.*</exclude>
                                    <exclude>com.minnced.*</exclude>
                                    <exclude>com.google.*</exclude>
                                    <exclude>com.googlecode.*</exclude>
                                    <exclude>com.neovisionaries.ws.client.*</exclude>
                                    <exclude>com.iwebpp.crypto</exclude>
                                    <exclude>net.md-5:bungeecord-chat:jar:1.8-SNAPSHOT</exclude>
                                    <exclude>junit</exclude>
                                    <exclude>mojang-translations.*</exclude>
                                    <exclude>gnu.trove</exclude>
                                    <exclude>net.java.*</exclude>
                                    <exclude>javax.*</exclude>
                                    <exclude>net.sf.*</exclude>
                                </excludes>
                            </artifactSet>
                            -->
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>com.zelix.plugins</groupId>
                <artifactId>zkm-plugin</artifactId>
                <version>1.0.4</version>
                <dependencies>
                    <dependency>
                        <groupId>com.zelix.plugins</groupId>
                        <artifactId>ZKM</artifactId>
                        <version>13.0.0</version>
                        <scope>system</scope>
                        <systemPath>C:/Users/Aidan/ZelixKlassmaster/ZKM.jar</systemPath>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals><goal>obfuscate</goal></goals>
                    </execution>
                </executions>
                <configuration>
                    <isSkip>false</isSkip>
                    <scriptFile>SuperReportZkmScript.txt</scriptFile>
                    <classpathLibs>
                        <lib>${java.home}/lib/rt.jar</lib>
                        <lib>D:\Java\apache-ant-1.9.2\lib\ant.jar</lib>
                    </classpathLibs>
                </configuration>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>


    <repositories>
        <repository>
            <id>jcenter</id>
            <name>jcenter</name>
            <url>https://jcenter.bintray.com/</url>
        </repository>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
        </repository>
        <repository>
            <id>spigot-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>net.dv8tion</groupId>
            <artifactId>JDA</artifactId>
            <version>4.2.0_227</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.8-R0.1-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot</artifactId>
            <version>1.11-R0.1-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>5.0.0-alpha.2</version>
        </dependency>

        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib</artifactId>
            <version>1.5.0-M2</version>
        </dependency>
    </dependencies>
</project>